#!/bin/sh

set -e

# 获取脚本自身的绝对路径（兼容 sh / bash source 执行）
if [ -n "$BASH_VERSION" ]; then
    SCRIPT_PATH="${BASH_SOURCE[0]}"
else
    SCRIPT_PATH="$0"
fi
SCRIPT_DIR=$(cd "$(dirname "$SCRIPT_PATH")" && pwd)

# $1有值用$1，无值默认用脚本所在的绝对目录
TARGET_DIR="${1:-$SCRIPT_DIR}"

cd "${TARGET_DIR}"

# ========== 备份旧 vimrc（带时间戳） ==========
OLD_VIMRC="$HOME/.vimrc"
BACKUP_TIME=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="$HOME/.vimrc.bak.${BACKUP_TIME}"

if [ -f "$OLD_VIMRC" ]; then
    cp "$OLD_VIMRC" "$BACKUP_FILE"
    echo ">> 已备份原有 vimrc 到: $BACKUP_FILE"
fi

# 生成新的 ~/.vimrc 配置文件
cat > ~/.vimrc <<EOF
" DO NOT EDIT THIS FILE
" Add your own customizations in ${TARGET_DIR}/my_configs.vim

" ========== Vim 内部全局变量：vim_runtime 根目录 ==========
" 仅在 Vim 进程内生效，不污染 Shell 系统环境
let g:VIM_RUNTIME_PATH = '${TARGET_DIR}'

set runtimepath+=${TARGET_DIR}

source ${TARGET_DIR}/vimrcs/basic.vim
source ${TARGET_DIR}/vimrcs/filetypes.vim
source ${TARGET_DIR}/vimrcs/plugins_config.vim
source ${TARGET_DIR}/vimrcs/extended.vim

try
  source ${TARGET_DIR}/my_configs.vim
catch
endtry
EOF

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"
echo "vim_runtime 根目录: ${TARGET_DIR}"
echo "已定义 Vim 内部变量 g:VIM_RUNTIME_PATH（不影响系统环境）"
